import 'package:flutter/material.dart';

class AppThemes {
  AppThemes._();

  static final lightTheme = ThemeData(
      useMaterial3: true,
      colorScheme: ColorScheme.fromSeed(
        seedColor: Color(0xff41ad4f),
        primary: Color(0xff006e22),
        onPrimary: Color(0xffffffff),
        scrim: Color(0xff000000),
        inversePrimary: Color(0xff71dd78),
        inverseSurface: Color(0xff2f312d),
        onInverseSurface: Color(0xfff0f1eb),
        outlineVariant: Color(0xffc2c9bd),
        shadow: Color(0xff000000),
        background: Color(0xfffcfdf7),
        onBackground: Color(0xff1a1c19),
        primaryContainer: Color(0xffb5f2b1),
        onPrimaryContainer: Color(0xff002105),
        secondary: Color(0xff52634f),
        onSecondary: Color(0xffffffff),
        secondaryContainer: Color(0xffd5e8cf),
        onSecondaryContainer: Color(0xff101f10),
        surface: Color(0xfffcfdf7),
        onSurface: Color(0xff1a1c19),
        surfaceTint: Color(0xff006e22),
        surfaceVariant: Color(0xffdee5d9),
        onSurfaceVariant: Color(0xff424940),
        error: Color(0xffba1a1a),
        onError: Color(0xffffffff),
        errorContainer: Color(0xffffdad6),
        onErrorContainer: Color(0xff410002),
        brightness: Brightness.light,
        tertiary: Color(0xff39656b),
        onTertiary: Color(0xffffffff),
        tertiaryContainer: Color(0xffbcebf1),
        onTertiaryContainer: Color(0xff001f23),
        outline: Color(0xff72796f),
        //shadow: Color(0xff000000),
      ),
      appBarTheme: AppBarTheme(
          backgroundColor: Colors.green.shade300,
          foregroundColor: Colors.black87,
          iconTheme: IconThemeData(color: Colors.black)));

  static final darkTheme = ThemeData(
    useMaterial3: true,
    colorScheme: ColorScheme.fromSeed(
      seedColor: Color(0xFF000000),
      primary: Color(0xFF9ECAFF),
      onPrimary: Color(0xFF003258),
      scrim: Color(0xFF9ECAFF),
      inversePrimary: Color(0xFFD1E4FF),
      inverseSurface: Color(0xFFD1E4FF),
      onInverseSurface: Color(0xFFD1E4FF),
      outlineVariant: Color(0xFF9ECAFF),
      shadow: Color(0xFF9ECAFF),
      background: Color(0xFF17191B),
      onBackground: Color(0xFFF5F5F6),
      primaryContainer: Color(0xFF00497D),
      onPrimaryContainer: Color(0xFFD1E4FF),
      secondary: Color(0xFFBBC7DB),
      onSecondary: Color(0xFF253140),
      secondaryContainer: Color(0xFF3B4858),
      onSecondaryContainer: Color(0xFFD7E3F7),
      surface: Color(0xFF17191B),
      onSurface: Color(0xFFE2E2E6),
      surfaceTint: Color(0xFFDADDE2),
      surfaceVariant: Color(0xFFB0B3BA),
      onSurfaceVariant: Color(0xFFD1E4FF),
      error: Color(0xFFFFB4AB),
      onError: Color(0xFF690005),
      errorContainer: Color(0xFF410002),
      onErrorContainer: Color(0xFFD1E4FF),
      brightness: Brightness.dark,
      tertiary: Color(0xFFD6BEE4),
      onTertiary: Color(0xFF3B2948),
      tertiaryContainer: Color(0xFF4A3956),
      onTertiaryContainer: Color(0xFFF2DAFF),
      outline: Color(0xFF9ECAFF),
      //shadow: Color(0xFF9ECAFF),
    ),
  );
}
